### PR TITLE
Layer: don't make a list out of glyph names

### PR DESCRIPTION
**Pull request by adrientetar**

### CODE REVIEW

**Comment by anthrotype** [comment]
I guess you want to avoid the extra copy when converting the `self._keys` set into a list.
But this could create problems for existing code that relies on keys() returning a list instead of a set.
Also note that defcon.Font.keys() method returns a list, as does ufoLib.GlyphSet.keys().
The thing is all these libraries were originally python2-only, where dict.keys() would return a list (copy) of the keys in a dictionary. When porting them to python3, we tried to keep the python2 behaviour.

**Comment by anthrotype** [comment]
sorry, I pressed the wrong button. I didn't mean to close the PR. I'm open to merge this if others say I'm worrying too much.

**Comment by adrientetar** [comment]
> But this could create problems for existing code that relies on keys() returning a list instead of a set.

What kind of code would rely on keys() being a list? The returned order is arbitrary, afaict.

> Also note that defcon.Font.keys() method returns a list

This is an alias to font.layers[defaultLayer].keys() – this pull request changes it, afaict.

**Comment by anthrotype** [comment]
you're right.

**Comment by anthrotype** [comment]
maybe the docstring should also be updated to explicitly say it now returns a set, for people who are used to get list from `keys`-like methods.

**Pull request merged**
