### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by benkiel**

### CODE REVIEW

**Comment by anthrotype** [comment]
where is fontPens used in defcon?

**Comment by typesupply** [comment]
> where is fontPens used in defcon?

[In the PR I opened.](https://github.com/typesupply/defcon/pull/174/files#diff-67cc6412b69b04769129aebc12c65ca7R5)

**Comment by anthrotype** [comment]
the FlattenPen, I see... :thinking: 
I don't know. I wish we could avoid adding a new required installation requirement (which for me, means an additional requirement to fontmake).

What about moving the import inside `contourFlattenedRepresentationFactory` (is that misspelled without a `y`?)?

So fontPens would only be required if one calls the method to correct the contour directions.

We could have an "extras_require" in the setup.py (e.g. called "pens"), so that one could do `pip install defcon[pens]` and get the extra requirement, in this case fontPens...

**Comment by benkiel** [comment]
Sounds good. Will close this.

**Pull request closed without merging**
