### PR TITLE
Rebuild layer._glyphSet when needed.

### PR DESCRIPTION
**Pull request by typesupply**
This addresses #209 and #218.

### CODE REVIEW

**Comment by typesupply** [comment]
Travis says this is failing in Python 2.7, but I don't understand why. Anyone able to figure it out?

**Comment by anthrotype** [comment]
https://travis-ci.org/typesupply/defcon/jobs/470065041#L974

`TypeError: paths must be unicode (not str)`

make sure you always pass unicode to fs API

**Comment by benkiel** [comment]
@anthrotype any idea why this fails on Windows, and if it matters (?)....

**Comment by anthrotype** [comment]
Of course it matters!

https://ci.appveyor.com/project/typesupply/defcon/builds/21125596/job/9pf8c96agkhkne89#L473

> WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'c:\\projects\\defcon\\.tox\\py\\lib\\site-packages\\defcon\\test\\testdata\\TestExternalEditingCopy.ufoz'

The `tearDownTestFontCopy` is calling `os.remove` on a file which is locked by Windows because a process (ourselves) still has a reference to it. While a Font instance exists, and has a ref to an open UFOReader that has a ref to an open FS object... one cannot remove the file on windows. One needs to close the FS object, thus releasing the resource...

**Comment by benkiel** [comment]
Beat me to it. I'll look at re-working the tests in a bit. At least Python 2.7 now is happy.

**Comment by anthrotype** [comment]
TBH I never liked they way the setup/teardown of the test font is done in defcon tests. Ideally test methods that require this setup/teardown code shold be grouped in a TestCase class, with setUp and tearDown method automatically doing their thing before/after each test method is run, and using a temporary directory, so that if one test method fails, the following ones don't fail just because clean up code didn't work on the previous failing tests..

**Comment by anthrotype** [comment]
currently defcon.Font instances need to keep a reference to self._reader (UFOReader instance) in order to implement the lazy-loading. But Font doesn't expose any API to close the reader and thus release the used filesystem resources. The UFOReader has a close() method (and can also be used as a contextmanager that auto-closes in a with statement). I think we need to add a close() method to Font as well, that calls self._reader.close(). Otherwise you can't call os.remove on the path used by the reader, at least until the Font and its reader are garbage collected.

**Comment by typesupply** [comment]
Can we make "add a close method to Font" and "rebuild the test suite" different issues? I think that is out of the scope of what this PR is addressing.

**Comment by anthrotype** [comment]
you're right, it's different.
BTW, this looks good to me.

**Comment by typemytype** [comment]
does the window issue has to be resolved before merging here?

```traceback
WindowsError: [Error 32] The process cannot access the file because it is being used by another process:
```

**Comment by typesupply** [comment]
> does the window issue has to be resolved before merging here?

No. That will be handled in a separate issue. I'll merge now.

**Pull request merged**
