### PR TITLE
Use more iterators

### PR DESCRIPTION
**Pull request by adrientetar**
As slicing makes a copy.

r? @typesupply

### CODE REVIEW

**Comment by anthrotype** [comment]
unrelated but, I just noticed the `Color` class has the python2-only `__cmp__` method, which is ignored by Python3; the built-in `cmp` function is also gone in Python3...

I guess we need to replace the `__cmp__` method with "rich comparison" methods...
http://python3porting.com/problems.html#unorderable-types-cmp-and-cmp

**Comment by adrientetar** [comment]
It doesn't make a lot of sense to compare colors as (r,g,b) tuples, I think. Maybe cmp should just be removed.

**Comment by anthrotype** [comment]
is it used anywhere?

**Comment by adrientetar** [comment]
I don't think so, maybe it was just put in because the parent class str implements comparison.

**Comment by anthrotype** [comment]
maybe it's used for sorting them, when serializing to UFO maybe, dunno

**Comment by anthrotype** [comment]
I think the idea of subclassing `str` is wrong in this case; a named tuple with a custom `__str__` metod would have done the same job, without having to call `_stringToSequence` every time one gets an attribute...

**Comment by adrientetar** [comment]
> maybe it's used for sorting them, when serializing to UFO

I don't understand what you mean by that. Either way, I think the semantics of tuple and string comparison are the same anyway (the compare test previously passed on both py2 and 3).

**Comment by anthrotype** [comment]
I guess you're right.

**Comment by anthrotype** [comment]
but I still think that it would make more sense for it to be a subclass of `collections.namedtuple` which takes either a string or tuple of floats, rounds the floats to 5 decimal position and stores them as such; and has a __str__ method for pretty-printing it... We could do that another time maybe.

**Comment by typesupply** [comment]
> maybe it's used for sorting them, when serializing to UFO maybe, dunno

The string subclass is there because the validator in ufoLib expects color definitions to be string instances. Iteration over the rgba values needs to be possible on these because parsing strings sucks. But, the object can't subclass tuple because ufoLib will choke. Thus, the `struple` was invented. If you have a better way to make a tuple subclass work in ufoLib, I'm 100% cool with getting rid of this hack.

The comparison function is there because, um, I don't know, it was fun to write?

**Comment by anthrotype** [comment]
Thanks Tal.
The PR looks good to me.

**Comment by anthrotype** [comment]
Let's merge it then

**Pull request merged**
